/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AuthenticNepaliModel;
import controller.AuthenticNepaliController;

/**
 *
 * @author User
 */
public class AuthenticNepali extends javax.swing.JFrame {
    PreparedStatement pst = null;
    AuthenticNepaliModel model;
    
     
    DefaultTableModel Model = null;

    

    /**
     * Creates new form AuthenticNepali
     */
    public AuthenticNepali() {
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Drinks = new javax.swing.JTable();
        Show = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AuthenticNepalistock = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        savedatabtn = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        itemName = new javax.swing.JTextField();
        ItemName = new javax.swing.JLabel();
        ItemNo = new javax.swing.JLabel();
        itemNo = new javax.swing.JTextField();
        Show1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(131, 197, 190));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Drinks.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Drinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Quantity", "Price"
            }
        ));
        Drinks.setColumnSelectionAllowed(true);
        Drinks.setGridColor(new java.awt.Color(216, 246, 210));
        Drinks.setOpaque(false);
        jScrollPane3.setViewportView(Drinks);

        Show.setText("Show Data");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(131, 197, 190));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Authentic Nepali Stocks", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        AuthenticNepalistock.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        AuthenticNepalistock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Quantity", "Price"
            }
        ));
        AuthenticNepalistock.setColumnSelectionAllowed(true);
        AuthenticNepalistock.setGridColor(new java.awt.Color(216, 246, 210));
        AuthenticNepalistock.setOpaque(false);
        jScrollPane4.setViewportView(AuthenticNepalistock);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(16, 101, 82));
        update.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update.setText("Update");
        update.setContentAreaFilled(false);
        update.setDefaultCapable(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        savedatabtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        savedatabtn.setText("Save Data");
        savedatabtn.setBorderPainted(false);
        savedatabtn.setContentAreaFilled(false);
        savedatabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        savedatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedatabtnActionPerformed(evt);
            }
        });

        price.setBackground(new java.awt.Color(131, 197, 190));
        price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        price.setAutoscrolls(false);
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        Price.setBackground(new java.awt.Color(131, 197, 190));
        Price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Price.setText("Price");

        Quantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Quantity.setText("Quantity");

        quantity.setBackground(new java.awt.Color(131, 197, 190));
        quantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        quantity.setAutoscrolls(false);
        quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        itemName.setBackground(new java.awt.Color(131, 197, 190));
        itemName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itemName.setAutoscrolls(false);
        itemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });

        ItemName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ItemName.setText("Item Name");

        ItemNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ItemNo.setText("Item No.");

        itemNo.setBackground(new java.awt.Color(131, 197, 190));
        itemNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itemNo.setAutoscrolls(false);
        itemNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        itemNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoActionPerformed(evt);
            }
        });

        Show1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Show1.setText("Show Stocks");
        Show1.setBorderPainted(false);
        Show1.setContentAreaFilled(false);
        Show1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ItemNo)
                                        .addComponent(ItemName)
                                        .addComponent(Quantity))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Price)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update)
                                .addGap(18, 18, 18)
                                .addComponent(savedatabtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Show1)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemNo))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemName))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantity))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(update)
                            .addComponent(savedatabtn)
                            .addComponent(Show1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) AuthenticNepalistock.getModel();

        if(AuthenticNepalistock.getSelectedRowCount() ==1){
             Model.removeRow(AuthenticNepalistock.getSelectedRow());
        }else{
            if(AuthenticNepalistock.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Stock is empty!!");
            }else{
                JOptionPane.showMessageDialog(this, "Please select Single row for deletion");
            }
        }

        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Model = (DefaultTableModel) AuthenticNepalistock.getModel();
        if(AuthenticNepalistock.getSelectedRowCount()==1){
            String ItemNo = itemNo.getText();
            String ItemName = itemName.getText();
            String Quantity = quantity.getText();
            String Price = price.getText();

            Model.setValueAt(ItemNo,AuthenticNepalistock.getSelectedRow(),0);
            Model.setValueAt(ItemName,AuthenticNepalistock.getSelectedRow(),1);
            Model.setValueAt(Quantity,AuthenticNepalistock.getSelectedRow(),2);
            Model.setValueAt(Price,AuthenticNepalistock.getSelectedRow(),3);

            JOptionPane.showMessageDialog(this, "Update Successfully!!");
        }else{
            if(AuthenticNepalistock.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Sotck is empty!!");
            }else{
                JOptionPane.showMessageDialog(this, "Please select single row for update!!");
            }
        }

    }//GEN-LAST:event_updateActionPerformed

    private void savedatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedatabtnActionPerformed
        // TODO add your handling code here:
        if(itemNo.getText().equals("") || itemName.getText().equals("") || quantity.getText().equals("") || price.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter all stocks");
        }else{
            String data[] = {itemNo.getText(),itemName.getText(),quantity.getText(),price.getText()};
            DefaultTableModel Model = (DefaultTableModel) AuthenticNepalistock.getModel();
            Model.addRow(data);
            
            try{
                String ItemNo,  ItemName, Quantity, Price;
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","asdfgzxcv123");
                for(int i = 0; i<Model.getRowCount();i++){
                    ItemNo = Model.getValueAt(i,0).toString();
                    ItemName = Model.getValueAt(i,1).toString();
                    Quantity = Model.getValueAt(i,2).toString();
                    Price = Model.getValueAt(i,3).toString();

                    String sql = "insert into authenticnepali(itemNo,itemName,quantity,price) values (?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1,ItemNo);
                    pst.setString(2,ItemName);
                    pst.setString(3,Quantity);
                    pst.setString(4,Price);

                    pst.execute();

                }

                    JOptionPane.showMessageDialog(this,"Stocks insert successfully!!");
                Model.setRowCount(0);
            }catch(Exception e){
            }
        }

       
    }//GEN-LAST:event_savedatabtnActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void itemNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        
    }//GEN-LAST:event_ShowActionPerformed

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // TODO add your handling code here:
                setAuthenticNepaliStock();
    }
    
    public void setAuthenticNepaliStock(){
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","asdfgzxcv123");
            PreparedStatement pst = con.prepareStatement("select * from authenticnepali");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String itemNo = rs.getString("itemNo");
                String itemName = rs.getString("itemName");
                String price = rs.getString("price");
                String quantity = rs.getString("Quantity");
                
                Object[] obj = {itemNo, itemName, quantity, price};
                
                Model = (DefaultTableModel)AuthenticNepalistock.getModel();
                Model.addRow(obj);
            }
            
            
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        
    }//GEN-LAST:event_Show1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new Inventory().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public AuthenticNepaliModel getData(){
        model = new AuthenticNepaliModel(itemNo.getText(), itemName.getText(), quantity.getText(), price.getText());
        return model;

        }
        
        public void setMessage(String msg){
            JOptionPane.showMessageDialog(this, msg);
        }
    
        public void saveAuthenticNepaliListner(ActionListener Save){
        savedatabtn.addActionListener(Save);
        }
        
        
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticNepali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticNepali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticNepali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticNepali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticNepali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable AuthenticNepalistock;
    public javax.swing.JTable Drinks;
    private javax.swing.JLabel ItemName;
    private javax.swing.JLabel ItemNo;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton Show;
    private javax.swing.JButton Show1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton savedatabtn;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}