/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DrinksModel;

/**
 *
 * @author User
 */
public class Drinks extends javax.swing.JFrame {
    PreparedStatement pst = null;
    DrinksModel model;
    Statement stmt = null;
    Connection conn = null;

    
     
    DefaultTableModel Model = null;

    /**
     * Creates new form Drinks
     */
    public Drinks() {
        initComponents();
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fastfoods = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        fastfoods1 = new javax.swing.JTable();
        Show1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Drinkstbl = new javax.swing.JTable();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        itemName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        itemNo = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        savedatabtn = new javax.swing.JButton();
        showbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        fastfoods.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fastfoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Quantity", "Price"
            }
        ));
        fastfoods.setColumnSelectionAllowed(true);
        fastfoods.setGridColor(new java.awt.Color(216, 246, 210));
        fastfoods.setOpaque(false);
        jScrollPane1.setViewportView(fastfoods);

        fastfoods1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fastfoods1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Quantity", "Price"
            }
        ));
        fastfoods1.setColumnSelectionAllowed(true);
        fastfoods1.setGridColor(new java.awt.Color(216, 246, 210));
        fastfoods1.setOpaque(false);
        jScrollPane2.setViewportView(fastfoods1);

        Show1.setText("Show Stocks");
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 190, 169));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drinks Stock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        Drinkstbl.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Drinkstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No.", "Item Name", "Quantity", "Price"
            }
        ));
        Drinkstbl.setColumnSelectionAllowed(true);
        Drinkstbl.setGridColor(new java.awt.Color(216, 246, 210));
        Drinkstbl.setOpaque(false);
        jScrollPane3.setViewportView(Drinkstbl);

        price.setBackground(new java.awt.Color(221, 190, 169));
        price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        price.setAutoscrolls(false);
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(131, 197, 190));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Price");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");

        quantity.setBackground(new java.awt.Color(221, 190, 169));
        quantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        quantity.setAutoscrolls(false);
        quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        itemName.setBackground(new java.awt.Color(221, 190, 169));
        itemName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itemName.setAutoscrolls(false);
        itemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Item No.");

        itemNo.setBackground(new java.awt.Color(221, 190, 169));
        itemNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itemNo.setAutoscrolls(false);
        itemNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        itemNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(16, 101, 82));
        updatebtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setContentAreaFilled(false);
        updatebtn.setDefaultCapable(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        savedatabtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        savedatabtn.setText("Save Data");
        savedatabtn.setBorderPainted(false);
        savedatabtn.setContentAreaFilled(false);
        savedatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedatabtnActionPerformed(evt);
            }
        });

        showbtn.setText("Show Stocks");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savedatabtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(updatebtn)
                            .addComponent(savedatabtn)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(showbtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void myreset(){
        itemNo.setText("");
        itemName.setText("");
        quantity.setText("");
        price.setText("");
    }
    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void itemNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       DefaultTableModel Model = (DefaultTableModel) Drinkstbl.getModel();

        if (Drinkstbl.getSelectedRowCount() == 1) {
            int selectedRow = Drinkstbl.getSelectedRow();
            String itemNoToDelete = Drinkstbl.getValueAt(selectedRow, 0).toString(); // Assuming itemNo is in the first column

            Model.removeRow(selectedRow);

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "asdfgzxcv123");
                Statement stmt = conn.createStatement();

                String sql = "DELETE FROM drinks WHERE itemNo = '" + itemNoToDelete + "'";
                stmt.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Data Deleted", "Drinks", JOptionPane.INFORMATION_MESSAGE);
                myreset();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a single row for deletion", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Model = (DefaultTableModel) Drinkstbl.getModel();
        int selectedRow = Drinkstbl.getSelectedRow();
        
        if (selectedRow == -1) {
            if (Drinkstbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Stock is empty!!");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row to update!!");
            }
        } else {
            String itemNoValue = itemNo.getText();
            String itemNameValue = itemName.getText();
            String quantityValue = quantity.getText();
            String priceValue = price.getText();

            Model.setValueAt(itemNoValue, selectedRow, 0);
            Model.setValueAt(itemNameValue, selectedRow, 1);
            Model.setValueAt(quantityValue, selectedRow, 2);
            Model.setValueAt(priceValue, selectedRow, 3);
            
            
            

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "asdfgzxcv123");

                String sql = "UPDATE drinks SET ItemNo=?, ItemName=?, Quantity=?, Price=? WHERE ItemNo=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, itemNoValue);
                pst.setString(2, itemNameValue);
                pst.setString(3, quantityValue);
                pst.setString(4, priceValue);
                pst.setString(5, itemNoValue); // Assuming 'ItemNo' is the primary key column

                pst.executeUpdate();
                pst.close();
                conn.close();

                JOptionPane.showMessageDialog(this, "Update Successful!!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savedatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedatabtnActionPerformed
        if (itemNo.getText().equals("") || itemName.getText().equals("") || quantity.getText().equals("") || price.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all stocks");
        } else {
            String data[] = { itemNo.getText(), itemName.getText(), quantity.getText(), price.getText() };
            DefaultTableModel Model = (DefaultTableModel) Drinkstbl.getModel();
            Model.addRow(data);
            JOptionPane.showMessageDialog(this, "Stock added successfully!!");
        }
        if (Drinkstbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Stock is Empty");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "asdfgzxcv123");

                String sql = "INSERT INTO drinks (itemNo, itemName, quantity, price) VALUES (?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);

                for (int i = 0; i < Drinkstbl.getRowCount(); i++) {
                    String itemNoValue = Drinkstbl.getValueAt(i, 0).toString();
                    String itemNameValue = Drinkstbl.getValueAt(i, 1).toString();
                    String quantityValue = Drinkstbl.getValueAt(i, 2).toString();
                    String priceValue = Drinkstbl.getValueAt(i, 3).toString();

                    pst.setString(1, itemNoValue);
                    pst.setString(2, itemNameValue);
                    pst.setString(3, quantityValue);
                    pst.setString(4, priceValue);

                    pst.executeUpdate();
                }

                pst.close();
                conn.close();

                JOptionPane.showMessageDialog(this, "Stocks inserted successfully!!");
                DefaultTableModel Model = (DefaultTableModel) Drinkstbl.getModel();
                Model.setRowCount(0); // Clear the table after successful insertion
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
       
    }//GEN-LAST:event_savedatabtnActionPerformed

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // TODO add your handling code here:
        setDrinksStock();
    
    }
    
    public void setDrinksStock(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","asdfgzxcv123");
            PreparedStatement pst = con.prepareStatement("select * from drinks");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String itemNo = rs.getString("itemN0");
                String itemName = rs.getString("itemName");
                String price = rs.getString("price");
                String quantity = rs.getString("Quantity");
                
                Object[] obj = {itemNo, itemName, quantity, price};
                
                Model = (DefaultTableModel)Drinkstbl.getModel();
                Model.addRow(obj);
            }
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_Show1ActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_showbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Inventory().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public DrinksModel getData(){
        DrinksModel model = new DrinksModel(itemNo.getText(), itemName.getText(), quantity.getText(), price.getText());
        return model;

        }
        
        public void setMessage(String msg){
            JOptionPane.showMessageDialog(this, msg);
        }
    
        public void saveDrinksListner(ActionListener Save){
        savedatabtn.addActionListener(Save);
        }
        
        public void deleteDrinksListner(ActionListener Delete){
            btnDelete.addActionListener(Delete);
        }
        
        public void updateDrinksListner(ActionListener Update){
            updatebtn.addActionListener(Update);
        }
        
        public void showDrinksListner(ActionListener Show){
            showbtn.addActionListener(Show);
        }
        
        
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Drinkstbl;
    private javax.swing.JButton Show1;
    private javax.swing.JButton btnDelete;
    public javax.swing.JTable fastfoods;
    public javax.swing.JTable fastfoods1;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton savedatabtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
